# Generated by Django 4.1.5 on 2023-01-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiModel', '0002_drug_names_delete_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='names',
            field=models.TextField(null=True),
        ),
    ]
