# Generated by Django 4.1.5 on 2023-01-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiModel', '0003_alter_drug_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='names',
        ),
    ]
