# Generated by Django 4.1.5 on 2023-01-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiModel', '0004_remove_drug_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='names',
            field=models.TextField(null=True),
        ),
    ]
